# Base path — Chiron, the wise teacher and mentor of heroes
quarkus.http.root-path=/chiron

# Datasource — Dev Services auto-starts PostgreSQL
quarkus.datasource.db-kind=postgresql
# Flyway
quarkus.flyway.migrate-at-start=true
%dev.quarkus.flyway.clean-at-start=true

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=none

