# Datasource — Dev Services auto-starts PostgreSQL
quarkus.datasource.db-kind=postgresql

# Hibernate — Flyway owns the schema
quarkus.hibernate-orm.database.generation=none

# Flyway
quarkus.flyway.migrate-at-start=true

# Logging — global level
quarkus.log.level=${LEVEL:INFO}

# Logging — app level (our code only)
quarkus.log.category."dev.learning".level=${APP_LEVEL:DEBUG}
