CREATE SEQUENCE Book_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE BookItem_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE Member_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE book_lending_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE Book (
    id BIGINT NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(13) NOT NULL UNIQUE,
    publisher VARCHAR(255),
    publishDate TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE Member (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    createdAt TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE BookItem (
    id BIGINT NOT NULL PRIMARY KEY,
    book_id BIGINT REFERENCES Book(id),
    status VARCHAR(255) NOT NULL CHECK (status IN ('AVAILABLE', 'LENT', 'UNAVAILABLE', 'DAMAGED')),
    notes VARCHAR(255),
    creationDate TIMESTAMP(6) WITH TIME ZONE,
    updateDate TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE book_lending (
    id BIGINT NOT NULL PRIMARY KEY,
    book_item_id BIGINT NOT NULL REFERENCES BookItem(id),
    member_id BIGINT NOT NULL REFERENCES Member(id),
    borrowed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    due_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    returned_at TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('AVAILABLE', 'LENT', 'RETURNED', 'LENT_EXPIRED'))
);
